"""Initial migration

Revision ID: 45f5a0083b1b
Revises: 
Create Date: 2024-12-08 07:53:55.003722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f5a0083b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteorological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('lower_threshold', sa.Float(), nullable=False),
    sa.Column('upper_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter')
    )
    op.create_table('water_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_quality')
    op.drop_table('threshold')
    op.drop_table('meteorological')
    # ### end Alembic commands ###
