"""empty message

Revision ID: dcf3c1c38bba
Revises: a56f0cd7e77e
Create Date: 2024-12-09 23:31:27.047791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf3c1c38bba'
down_revision = 'a56f0cd7e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('water_quality', sa.FLOAT(), nullable=False),
    sa.Column('atmospheric_conditions', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
